### ISSUE TITLE
Implement accelerate feature for eth based transactions

### ISSUE THREAD

**Issue by mNizhurin** [horizontalsystems/ethereum-kit-ios#192] opened 2020-09-09 12:46 UTC
When transaction is stuck in pending state, user might need to rebroadcast it with same or higher fee.

To rebroadcast transaction use same nonce.

**Comment by esengulov** [comment] 2021-08-10 11:19
Duplicate of # https://github.com/horizontalsystems/unstoppable-wallet-ios/issues/2097

**Closed by esengulov** 2021-08-10 11:19 UTC
